project: 
  type: website
  output-dir: docs
  render: 
    - "*.qmd"
    - "!draft-*.qmd"

website: 
  title: "Arrow and DuckDB"
  navbar: 
    left: 
      - href: index.qmd
        text: Home
  sidebar: 
    contents: auto

format: 
  html: 
    theme:
      light: flatly
      dark: darkly
    toc: true
    toc-location: right-body
    highlight-style: github
    smooth-scroll: true
    code-copy: true
    code-link: true
   